# Dockerfile.front

# 단계 1: 빌드 단계
FROM node:14 AS builder

# 작업 디렉토리 설정
WORKDIR /app

# 패키지 설치
COPY package*.json ./
RUN npm install

# 애플리케이션 소스 복사
COPY . .

# 환경 변수 설정
ARG REACT_APP_API_URL
ENV REACT_APP_API_URL=${REACT_APP_API_URL}

# 애플리케이션 빌드
RUN npm run build

# 단계 2: 실행 단계
FROM nginx:alpine

# Nginx 설정 복사
COPY --from=builder /app/build /usr/share/nginx/html

# 컨테이너가 시작될 때 실행될 명령어 설정
CMD ["nginx", "-g", "daemon off;"]
